# Generated by Django 3.2.7 on 2022-04-10 15:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyContact',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(default='Lagos/Nigeria', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=2348037286666, max_length=128, region=None),
        ),
    ]
